workflows:
    android-workflow-id:
        name: Android Sample Workflows
          
        environment:
            android_signing:
              - keystore: anton
              keystore_environment_variable: RocketLaunchApp\codemagic.keystore
              keystore_password_environment_variable: keytool_password
              key_alias_environment_variable: codemagic
              key_password_environment_variable: key_password